### ISSUE TITLE
Support for UE 5.2

### ISSUE THREAD

**Issue by tprochazka** [PipeRift/SaveExtension#85]
It is currently not possible to compile with UE 5.2

```
...\SaveExtension\Build\HostProject\Plugins\SaveExtension\Source\SaveExtension\Private\SlotInfo.cpp(39): error C2027: use of undefined type 'FTexture2DMipMap'
...\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(739): note: see declaration of 'FTexture2DMipMap'
...\SaveExtension\Build\HostProject\Plugins\SaveExtension\Source\SaveExtension\Private\SlotInfo.cpp(41): error C2027: use of undefined type 'FTexture2DMipMap'
...\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(739): note: see declaration of 'FTexture2DMipMap'
...\SaveExtension\Build\HostProject\Plugins\SaveExtension\Source\SaveExtension\Private\SlotInfo.cpp(75): error C2027: use of undefined type 'FViewport'
...\UE_5.2\Engine\Source\Runtime\Engine\Public\EngineUtils.h(25): note: see declaration of 'FViewport'
```

**Comment by muit** [comment]
Hi,
I'm updating to 5.2 in #88, 5.3 will come soon too

Since it comes with multiple architecture changes it is unstable for now.

Thank you for the report :)
muit
